# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11250353b2fdc1d876e7387bf6fb9a343f671d5c64b58ca462708b6f9fe04fb0127cb72f9bc9a51a159c53078dec6fc1e9fae7cea13333cfac33a5d0ffc4c1c8

test:
  secret_key_base: 60ba119c3e5ce81d4d8bd1689a57cf44efeb1e7a56e1c01a31498e25d36c53284a3f7b66ed1f8ee8b79aa07554642db72948d1afdc95668e129d2d4cdd6072d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
